

apiVersion: v1
kind: Service
metadata:
  name: rocketmq
  labels:
    app: rocketmq
spec:
  type: NodePort
  ports:
    - port: 9876
      targetPort: 9876
      nodePort: 30876
      name: rmqser
    - port: 30911
      targetPort: 30911
      nodePort: 30911
      name: rmqbroker
    - port: 30921
      targetPort: 30921
      nodePort: 30921
      name: rmqbrokerslave
    - port: 30931
      targetPort: 30931
      nodePort: 30931
      name: rmqbrokerslave2
  selector:
    app: rocketmq