apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  mysql.master.db.name: "nacos"
  mysql.master.port: "3306"
  mysql.slave.port: "3306"
  mysql.master.user: "root"
  mysql.master.password: "root"
  mysql.master.host: "mariadb-0.mariadb.default.svc.cluster.local"
  mysql.slave.host: "mariadb-0.mariadb.default.svc.cluster.local"