

apiVersion: v1
kind: Service
metadata:

  name: xxl-job
  labels:
    app: xxl-job
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30820
      name: web
  selector:
    app: xxl-job