apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-cm
data:
  sentinel.server.host: "192.168.0.254"
  sentinel.server.port: "8280"
  sentinel.auth.username: "sentinel"
  sentinel.auth.password: "sentinel"