

apiVersion: v1
kind: Service
metadata:

  name: logstash
  labels:
    app: logstash
spec:
  type: NodePort
  ports:
    - port: 5621
      targetPort: 5621
      nodePort: 30621
  selector:
    app: logstash