

apiVersion: v1
kind: Service
metadata:

  name: hub-ui
  labels:
    app: hub-ui
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30501
  selector:
    app: registry-ui
