

apiVersion: v1
kind: Service
metadata:

  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30601
  selector:
    app: kibana