apiVersion: apps/v1
kind: StatefulSet
metadata:

  name: redis
  labels:
    app: redis
  annotations:
    security.alpha.kubernetes.io/unsafe-sysctls: net.core.somaxconn=65535
spec:
  #securityContext:
    #privileged: true
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        #net:
          #core:
            #somaxconn=511:
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 450m
              memory: 4000Mi
            requests:
              cpu: 400m
              memory: 4000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
          command: ["redis-server","/usr/local/etc/redis/redis.conf","--appendonly yes"]
#          lifecycle:
#            postStart:
#              exec:
#                command: ["/bin/bash", "-c", "echo 511 > /proc/sys/net/core/somaxconn; echo never > /sys/kernel/mm/transparent_hugepage/enabled;"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: vol-conf
              mountPath: /usr/local/etc/redis
            - name: vol-data
              mountPath: /data
      volumes:
        - name: vol-conf
          hostPath:
            path: /www/k8s/foxdev/redis/conf
            type: Directory
        - name: vol-data
          hostPath:
              path: /www/k8s/foxdev/redis/data
              type: Directory
