version: '3.1'
services:
  laputa-mysql:
#    build:
#      context: ./db
    image: mysql
    restart: always
    container_name: laputa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_connections=1000
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql_data:/var/lib/mysql
      - ./mysql/db/:/docker-entrypoint-initdb.d/
    networks:
      - laputa
networks:
  laputa:
    external: true


