version: '2'
services:
  # 模拟一个正常的mysql数据库
  mysql8:
    image: mysql:8.0.24
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
       - ./data/mysql/logs:/var/log/mysql
       - ./data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --lower_case_table_names=1
    networks:
      - laputa-net

  nacos:
    image: nacos/nacos-server
    container_name: nacos
    volumes:
      - ./nacos/standalone-logs/:/home/nacos/logs
    env_file:
      - ./nacos/nacos-standlone-mysql.env #这个文件指定启动模式  只有一行内容：MODE=standalone
    environment:
      - db.url.0=jdbc:mysql://mysql8:3306/base_config?Unicode=true&characterEncoding=UTF-8
      - spring.datasource.platform=mysql
      - db.user=root
      - db.password=root
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9255:9555"
    depends_on:
      - mysql8
    restart: always
    networks:
      - laputa-net

networks:
  laputa-net:
    driver: bridge