version: '2.0'
services:
   laputa-mq-namesrv:
    image: rocketmqinc/rocketmq
    container_name: laputa-mq-namesrv
    restart: always
    ports:
      - 9876:9876
    volumes:
      - ./logs:/home/rocketmq/logs
      - ./store:/home/rocketmq/store
    command: sh mqnamesrv
    networks:
      - laputa
  laputa-mq-broker:
    image: rocketmqinc/rocketmq
    container_name: rmqbroker
    restart: always
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./logs:/home/rocketmq/logs
      - ./store:/home/rocketmq/store
      - ./conf/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
    #command: sh mqbroker -n namesrv:9876
    command: sh mqbroker -n laputa-mq-namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - laputa-mq-namesrv
    environment:
      - JAVA_HOME=/usr/lib/jvm/jre
    networks:
      - laputa
  laputa-mq-console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console-ng
    restart: always
    ports:
      - 8076:8080
    depends_on:
      - laputa-mq-namesrv
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=laputa-mq-namesrv:9876
      - Dcom.rocketmq.sendMessageWithVIPChannel=false
    networks:
      - laputa
      
networks:
  laputa:
    external: true


