

apiVersion: v1
kind: Service
metadata:

  name: rmqbroker
  labels:
    app: rmqbroker
spec:
  type: NodePort
  ports:
    - port: 30909
      targetPort: 30909
      nodePort: 30909
      name: slave-master
    - port: 30911
      targetPort: 30911
      nodePort: 30911
      name: listen
    - port: 30912
      targetPort: 30912
      nodePort: 30912
      name: ha-service
  selector:
    app: rmqbroker