

apiVersion: v1
kind: Service
metadata:

  name: rocketmq
  labels:
    app: rocketmq
spec:
  type: NodePort
  ports:
    - port: 9876
      targetPort: 9876
      nodePort: 30876
  selector:
    app: rocketmq